name: chatpye-instance
machineType: e2-medium
zone: us-central1-a
tags:
  - http-server
  - https-server
metadata:
  items:
    - key: startup-script
      value: |
        #!/bin/bash
        # Download startup script
        curl -o /tmp/startup-script.sh https://raw.githubusercontent.com/joboyebisi/chatpye/main/startup-script.sh
        chmod +x /tmp/startup-script.sh
        /tmp/startup-script.sh
disks:
  - deviceName: boot
    type: PERSISTENT
    boot: true
    autoDelete: true
    initializeParams:
      sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
      diskSizeGb: 20
networkInterfaces:
  - network: global/networks/default
    accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
serviceAccounts:
  - email: default
    scopes:
      - https://www.googleapis.com/auth/cloud-platform 